#!/bin/bash


realpath() {
  readlink -f "$1" 2> /dev/null || python2.7 -c 'import os,sys; print os.path.realpath(sys.argv[1])' "$1"
}

_dirname=$( dirname $(realpath "$0") )
_projdir=$( cd "$_dirname/.." && pwd )


usage() {
    cat <<_EOF
Usage: publish <version>

Packages this project for release as a cordova plugin, then commits it to the
release-for-plugman branch with a <version> tag.

Examples:

publish 1.0.0
publish 1.0.1
_EOF
}


main() {
  set -e

  local version="$1"
  if [[ ! $version ]]; then
    echo 'Version is required!'
    usage
    exit 1
  fi

  set -x

  pushd "$projdir"
  local ref=$( git rev-parse HEAD )
  ./_make/dist

  pushd dist
  local tmp_dir=$( mktemp -d )
  zip -r "$tmp_dir/cordova-bluetoothle.zip" ./*
  popd

  git checkout release-for-plugman
  git ls-files | xargs git rm

  local before=$( find . -maxdepth 1 )
  unzip "$tmp_dir/cordova-bluetoothle.zip"
  local after=$( find . -maxdepth 1 )

  git add $( comm -13 <(echo "$before") <(echo "$after") )
  git commit -m "Release $version - based on $ref"
  git tag "v$version"

  rm -Rf "$tmp_dir"
}


main "$@"
