#!/bin/bash

_dirname=$( dirname $(python2.7 -c "import os,sys; print os.path.realpath('${BASH_SOURCE[0]}')") )

main() {
  set -ex

  cd "$_dirname"

  ./_scripts/get-js-dependencies
  source ./_scripts/set-js-paths

  if [[ ! -e ./testrunner ]]; then
    mkdir "$_dirname/testrunner"
    cd "$_dirname/testrunner"
    cordova create . com.mutualmobile.cordova BluetoothleTestRunner
  fi

  cd "$_dirname/testrunner"

  case "$1" in
    android)
      cordova platform add android || true
      ;;
    ios)
      cordova platform add ios || true
      ;;
  esac

  cordova plugin add "$_dirname/src" --link

  # remove www dirs. in development, we'll be loading html/js from a web
  # server instead.
  IFS=$'\n'
  for www_dir in $(find "$_dirname/testrunner" -name www -type d | grep 'plugins/com.mutualmobile.cordova.bluetoothle'); do
    rm -Rf "$www_dir"
  done

  cd "$_dirname"

  ./_scripts/set-config-url

  case "$1" in
    android)
      cd "$_dirname"
      ./_scripts/get-android-dependencies
      source ./_scripts/set-android-paths
      cd "$_dirname/testrunner/platforms/android"
      ./cordova/build --device
      ;;
    ios)
      cd "$_dirname/testrunner/platforms/ios"
      ./cordova/build --device
      ;;
  esac

}

main "$@"
