#!/bin/bash

_dirname=$( dirname $(python2.7 -c "import os,sys; print os.path.realpath('${BASH_SOURCE[0]}')") )

main() {
  set -ex

  cd "$_dirname"

  ./_scripts/get-js-dependencies
  source ./_scripts/set-js-paths

  cd "$_dirname/src"
  npm publish
}

main "$@"
