#!/bin/bash

_dirname=$( dirname $(python2.7 -c "import os,sys; print os.path.realpath('${BASH_SOURCE[0]}')") )


detect_platform() {
  cd "$_dirname/testrunner"

  android_device_count=$( cordova run android --list --device | wc -l )
  if [[ -d platforms/android && $android_device_count -gt 1 ]]; then
    printf 'android'
    return
  fi

  if [[ $OSTYPE != darwin* ]]; then
    return
  fi

  ios_device_count=$( cordova run ios --list --device | wc -l )
  if [[ -d platforms/ios && $ios_device_count -gt 1 ]]; then
    printf 'ios'
    return
  fi
}


main() {
  set -ex
  local platform="$1"

  cd "$_dirname"
  ./_scripts/get-js-dependencies
  source ./_scripts/set-js-paths
  ./_scripts/set-config-url

  if [[ ! $platform ]]; then
    platform=$( detect_platform )
  fi

  case $platform in
    android)
      cd "$_dirname/testrunner/platforms/android"
      ./cordova/run --device
      ;;
    ios)
      cd "$_dirname/testrunner/platforms/ios"
      ./cordova/run --device
      ;;
    *)
      printf 'No devices detected. Must specify either "./run android" or "./run ios"\n'
      exit 1
      ;;
  esac
}


main "$@"
