#!/bin/bash

_dirname=$( dirname $(python2.7 -c "import os,sys; print os.path.realpath('${BASH_SOURCE[0]}')") )
project_root="$( cd "$_dirname" && pwd )"

main() {
  set -ex

  cd "$project_root"
  ./_scripts/set-config-url
  ./dependencies/node_modules/http-server/bin/http-server -p 8000 -c-1 &

  source ./_scripts/set-js-paths
  export NODE_PATH="$project_root/dependencies/node_modules"
  node "$project_root/simulator/server.js" &

  wait
}

main "$@"
